In [ ]:
import pandas as pd
# Chargement des données
data = pd.DataFrame({
    "Fromages": ["CarredelEst", "Babybel", "Beaufort", "Bleu", "Camembert", "Cantal", "Chabichou", "Chaource", "Cheddar", "Comte",
                 "Coulomniers", "Edam", "Emmental", "Fr,chevrepatemolle206", "Fr,fondu,45", "Fr,frais20nat", "Fr,frais40nat",
                 "Maroilles", "Morbier", "Parmesan", "Petitsuisse40", "PontlEveque", "Pyrenees", "Reblochon", "Rocquefort", 
                 "SaintPaulin", "Tome", "Vacherin", "Yaourtlaitent,nat"],
    "Calories": [314, 314, 401, 342, 264, 367, 344, 292, 406, 399, 308, 327, 378, 206, 292, 80, 115, 338, 347, 381, 142, 300,
                 355, 309, 370, 298, 321, 321, 70],
    "Sodium": [353.5, 238, 112, 336, 314, 256, 192, 276, 172, 92, 222, 148, 60, 160, 390, 41, 25, 311, 285, 240, 22, 223,
               232, 272, 432, 205, 252, 140, 91],
    "Calcium": [72.6, 209.8, 259.4, 211.1, 215.9, 264, 87.2, 132.9, 182.3, 220.5, 79.2, 272.2, 308.2, 72.8, 168.5, 146.3, 94.8,
                236.7, 219, 334.6, 78.2, 156.7, 178.9, 202.3, 162, 261, 125.5, 218, 215.7],
    "Lipides": [26.3, 25.1, 33.3, 28.9, 19.5, 28.8, 27.9, 25.4, 32.5, 32.4, 25.6, 24.7, 29.4, 18.5, 24, 3.5, 7.8, 29.1, 29.5, 27.5,
                10.4, 23.4, 28, 24.6, 31.2, 23.3, 27.3, 29.3, 3.4],
    "Retinol": [51.6, 63.7, 54.9, 37.1, 103, 48.8, 90.1, 116.4, 76.4, 55.9, 63.6, 65.7, 56.3, 150.5, 77.4, 50, 64.3, 46.7, 57.6,
                 90, 63.4, 53, 51.5, 73.1, 83.5, 60.4, 62.3, 49.2, 42.9],
    "Folates": [30.3, 6.4, 1.2, 27.5, 36.4, 5.7, 36.3, 32.5, 4.9, 1.3, 21.1, 5.5, 2.4, 31, 5.5, 20, 22.6, 3.6, 5.8, 5.2, 20.4,
                 4, 6.8, 8.1, 13.3, 6.7, 6.2, 3.7, 2.9],
    "Protéines": [21, 22.6, 26.6, 20.2, 23.4, 23, 19.5, 17.8, 26, 29.2, 20.5, 24.7, 29.4, 11.1, 16.8, 8.3, 7, 20.4, 23.6, 35.7, 9.4,
                   21.1, 22.4, 19.7, 18.7, 23.3, 21.8, 17.6, 4.1],
    "Cholestérol": [70, 70, 120, 90, 60, 90, 80, 70, 110, 120, 80, 80, 110, 50, 70, 10, 30, 90, 80, 80, 20, 70, 90, 80, 100, 70,
                      80, 80, 13]
})

X = data.iloc[:, 1:] # Les autres colonnes sauf "Fromages"
y = data["Fromage"] # La colonne "Fromages"
# Affichage des premières lignes pour vérification
data.head()

In [5]:
# Description des données
print("\nDescription des données :")
data.describe()

Description des données :

,Calories,Sodium,Calcium,Lipides,Retinol,Folates,Protéines,Cholestérol
count,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000
mean,300.034483,210.086207,185.734483,24.158621,67.562069,13.010345,20.168966,74.586207
std,91.914356,108.678923,72.528882,8.129642,24.163098,11.723339,6.959788,28.245755
min,70.000000,22.000000,72.600000,3.400000,37.100000,1.200000,4.100000,10.000000
25%,292.000000,140.000000,132.900000,23.400000,51.600000,4.900000,17.800000,70.000000
50%,321.000000,223.000000,202.300000,26.300000,62.300000,6.400000,21.000000,80.000000
75%,355.000000,276.000000,220.500000,29.100000,76.400000,21.100000,23.400000,90.000000
max,406.000000,432.000000,334.600000,33.300000,150.500000,36.400000,35.700000,120.000000

In [ ]:


# Fonction de prédiction
def predict_fromages_class(Calories, Sodium, Calcim, Lipides,Retinol,Folates,Protéines,Cholestérol):
    # Normalisation des caractéristiques
    scaled_data = scaler.transform([[Calories, Sodium, Calcim, Lipides,Retinol,Folates,Protéines,Cholestérol]])

    # Prédiction de la classe
    predicted_class = knn.predict(scaled_data)

    # Conversion du code de la classe en nom de fromages
    fromage = {0: 'Classe 0',1: 'Classe 1',2: 'Classe 2',3: 'Classe 3',4: 'Other',}
    fromage = fromage[predicted_class[0]]

    return fromage

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# Liste pour stocker les valeurs de l'inertie
inertia = []

# Tester différentes valeurs de K pour l'algorithme K-means
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

# Tracer la courbe du coude
plt.plot(range(1, 11), inertia, marker='o')
plt.xlabel('Nombre de clusters (K)')
plt.ylabel('Inertie')
plt.title('Méthode du coude pour trouver K (Jeu de données Iris)')
plt.show()

In [ ]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalisation des caractéristiques (optionnel mais souvent recommandé pour k-NN)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



kmeans = KMeans(n_clusters=5, random_state=42)  # par exemple, choisissez le nombre de clusters approprié

# Entraînement du modèle
#kmeans.fit(X_train)

# Prédiction sur les données de test
#y_pred = kmeans.predict(X_test)



# Initialisation du classificateur k-NN avec k=3 (par exemple)
#knn = KNeighborsClassifier(n_neighbors=3)

# Entraînement du modèle
kmeans.fit(X_train, y_train)

# Prédiction sur les données de test
y_pred = kmeans.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

# Évaluation des performances
accuracy = accuracy_score(y_test, y_pred)
print("Précision du modèle : {:.2f}%".format(accuracy * 100))
print("Précision du modèle avec Knn : {:.2f}%".format(knn.score(X_test,y_test)))

In [ ]:

# Utilisation de la fonction de prédiction
CarredelEst = input("La valeur de CarredelEst")
Babybel = input("La valeur de Babybel")
Beaufort = input("La valeur de Beaufort")
Bleu = input("La valeur de Bleu")
Camembert = input("La valeur de Camembert")
Cantal = input("La valeur de Cantal")
Chabichou = input("La valeur de Chabichou")
Chaource = input("La valeur de Chaource")
Cheddar = input("La valeur de Cheddar")
Comte = input("La valeur de Comte")
Coulomniers = input("La valeur de Coulomniers")
Edam = input("La valeur de Edam")
Emmental = input("La valeur de Emmental")
Frchevrepatemolle206 = input("La valeur de Frchevrepatemolle206")
Frfondu45 = input("La valeur de Frfondu45")
Frfrais20nat = input("La valeur de Frfrais20nat")
Frfrais40nat = input("La valeur de Frfrais40nat")
Maroilles = input("La valeur de Maroilles")
Morbier = input("La valeur de Morbier")
Parmesan = input("La valeur de Parmesan")
Petitsuisse40 = input("La valeur de Petitsuisse40")
PontlEveque = input("La valeur de PontlEveque")
Pyrenees = input("La valeur de Pyrenees")
Reblochon = input("La valeur de Reblochon")
Rocquefort = input("La valeur de Rocquefort")
SaintPaulin = input("La valeur de SaintPaulin")
CarredelEst = input("La valeur de Tome")
CarredelEst = input("La valeur de Vacherin")
CarredelEst = input("La valeur de Yaourtlaitentnat")


predicted_fromages = predict_fromages_class( CarredelEst,Babybel,Beaufort,Bleu,Camembert, Cantal,Chabichou, Chaource,
                                        Cheddar,Comte,Coulomniers,Edam,Emmental,Frchevrepatemolle206,Frfondu45,Frfrais20nat,
                                        Frfrais40nat,Maroilles,Morbier,Parmesan,Petitsuisse40,PontlEveque,Pyrenees,Reblochon,
                                        Rocquefort,SaintPaulin,Tome,Vacherin,Yaourtlaitentnat)
print("Classe prédite pour les valeurs données : ", predicted_fromages)